#### glance service

apiVersion: v1
kind: Service
metadata:
  name: glance
  labels:
    app: glance
spec:
  ports:
    - port: 9292
      name: glance
  selector:
    app: glance
---

#### glance replication controller

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: glance
  name: glance
spec:
  selector:
    app: glance
  template:
    metadata:
      labels:
        app: glance
    spec:
      containers:
      - image: glance:v0.1
        imagePullPolicy: Never
        name: glance
        ports:
        - containerPort: 9292
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/glance/images
          name: glance-images-dir
      volumes:
      - name: glance-images-dir
        hostPath:
          path: /opt/glance-images

