#### neutron service

apiVersion: v1
kind: Service
metadata:
  name: neutron
  labels:
    app: neutron
spec:
  ports:
    - port: 9696
      name: neutron
  selector:
    app: neutron
---

#### neutron replication controller

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: neutron
  name: neutron
spec:
  selector:
    app: neutron
  template:
    metadata:
      labels:
        app: neutron
    spec:
      containers:
      - image: neutron:v0.1
        imagePullPolicy: Never
        securityContext:
          privileged: true
        name: neutron
        ports:
        - containerPort: 9696
          protocol: TCP

