#### horizon service

apiVersion: v1
kind: Service
metadata:
  name: horizon
  labels:
    app: horizon
spec:
  ports:
    - port: 80
      name: horizon
  selector:
    app: horizon
---

#### horizon replication controller

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: horizon
  name: horizon
  namespace: default
spec:
  selector:
    app: horizon
  template:
    metadata:
      labels:
        app: horizon
    spec:
      containers:
      - image: REGISTRY/horizon
        imagePullPolicy: Always
        name: horizon
        ports:
        - containerPort: 80
          protocol: TCP
